import React from "react";
import { Helmet } from "react-helmet";
import MontenHeader from "../partials/MontenHeader";

function MontenPrivacyPolicy() {
  return (
    <>
      <Helmet>
        <meta
          name="description"
          content="A new platform we created for information providers and receivers."
        />
        <meta property="og:title" content="Monten - Learn trending topics" />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content="https://firebasestorage.googleapis.com/v0/b/seewhatgodsays.appspot.com/o/static%2Fmonten-logo.png?alt=media&token=f3f3ba18-b186-4bce-b21a-bfb8531cbb16&_gl=1*11d8gj1*_ga*MTkwNDg3MDIxMS4xNjc2ODk3OTE5*_ga_CW55HF8NVT*MTY5OTM3MDA4OS42MC4xLjE2OTkzNzA2NTMuMjYuMC4w"
        />
        <meta
          property="og:url"
          content="https://www.creativemashimashi.com/monten"
        />
        <meta
          property="og:description"
          content="A new iOS app we created for learning trending topics."
        />
      </Helmet>
      <div className="flex flex-col min-h-screen overflow-hidden">
        {/*  Site header */}
        <MontenHeader />
        {/*  Page content */}
        <main className="px-6 md:px-36 pt-32 md:pt-52 bg-white flex flex-col xl:flex-row xl:justify-between font-inter">
          <div>
            <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
            <p className="mb-4">
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>
            <p className="mb-4">
              We use Your Personal data to provide and improve the Service. By
              using the Service, You agree to the collection and use of
              information in accordance with this Privacy Policy. Interpretation
              and Definitions.
            </p>

            <h2 className="text-2xl font-bold mt-6 mb-3">Interpretation</h2>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <h2 className="text-2xl font-bold mt-6 mb-3">Definitions</h2>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside mb-4">
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company",
                "We", "Us" or "Our" in this Agreement) refers to
                creativemashimashi.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your
                computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website
                among its many uses.
              </li>
              <li>
                <strong>Country</strong> refers to: Japan
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is
                used.
              </li>
              <li>
                <strong>Third-party Social Media Service</strong> refers to any
                website or any social network website through which a User can
                log in or create an account to use the Service.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li>
                <strong>Website</strong> refers to creativemashimashi,
                accessible from http://creativemashimashi.com
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>

            <h1 className="text-3xl font-bold mb-4">
              Collecting and Using Your Personal Data
            </h1>
            <h2 className="text-2xl font-bold mt-6 mb-3">
              Types of Data Collected
            </h2>
            <h3 className="text-xl font-bold mt-6 mb-3">Personal Data</h3>
            <p className="mb-4">
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li>
                <strong>Email address</strong>
              </li>
              <li>
                <strong>First name and last name</strong>
              </li>
              <li>
                <strong>Usage Data</strong>
              </li>
            </ul>
            <h2 className="text-2xl font-bold mt-6 mb-3">Usage Data</h2>
            <p className="mb-4">
              Usage Data is collected automatically when using the Service.
              Usage Data may include information such as Your Device's Internet
              Protocol address (e.g. IP address), browser type, browser version,
              the pages of our Service that You visit, the time and date of Your
              visit, the time spent on those pages, unique device identifiers
              and other diagnostic data. When You access the Service by or
              through a mobile device, We may collect certain information
              automatically, including, but not limited to, the type of mobile
              device You use, Your mobile device unique ID, the IP address of
              Your mobile device, Your mobile operating system, the type of
              mobile Internet browser You use, unique device identifiers and
              other diagnostic data. We may also collect information that Your
              browser sends whenever You visit our Service or when You access
              the Service by or through a mobile device.
            </p>
            <h2 className="text-2xl font-bold mt-6 mb-3">
              Tracking Technologies and Cookiess
            </h2>
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information. Tracking
              technologies used are beacons, tags, and scripts to collect and
              track information and to improve and analyze Our Service. The
              technologies We use may include:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li>
                <strong>Cookies or Browser Cookies.</strong> A cookie is a small
                file placed on Your Device. You can instruct Your browser to
                refuse all Cookies or to indicate when a Cookie is being sent.
                However, if You do not accept Cookies, You may not be able to
                use some parts of our Service. Unless you have adjusted Your
                browser setting so that it will refuse Cookies, our Service may
                use Cookies.
              </li>
              <li>
                <strong>Flash Cookies.</strong> Certain features of our Service
                may use local stored objects (or Flash Cookies) to collect and
                store information about Your preferences or Your activity on our
                Service. Flash Cookies are not managed by the same browser
                settings as those used for Browser Cookies. For more information
                on how You can delete Flash Cookies, please read "Where can I
                change the settings for disabling, or deleting local shared
                objects?" available at{" "}
                <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects">
                  https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects
                </a>
              </li>
              <li>
                <strong>Web Beacons.</strong> Certain sections of our Service
                and our emails may contain small electronic files known as web
                beacons (also referred to as clear gifs, pixel tags, and
                single-pixel gifs) that permit the Company, for example, to
                count users who have visited those pages or opened an email and
                for other related website statistics (for example, recording the
                popularity of a certain section and verifying system and server
                integrity).
              </li>
            </ul>
            <p className="mb-4">
              Cookies can be "Persistent" or "Session" Cookies. Persistent
              Cookies remain on Your personal computer or mobile device when You
              go offline, while Session Cookies are deleted as soon as You close
              Your web browser. You can learn more about cookies here:{" "}
              <a href="https://www.termsfeed.com/blog/cookies/">
                All About Cookies by TermsFeed
              </a>
              .
            </p>
            <p className="mb-4">
              We use both Session and Persistent Cookies for the purposes set
              out below:
            </p>
            <li>
              <strong>Necessary / Essential Cookies</strong>
              <p className="mb-4">Type: Session Cookies</p>
              <p className="mb-4">Administered by: Us </p>
              <p className="mb-4">
                Purpose: These Cookies are essential to provide You with
                services available through the Website and to enable You to use
                some of its features. They help to authenticate users and
                prevent fraudulent use of user accounts. Without these Cookies,
                the services that You have asked for cannot be provided, and We
                only use these Cookies to provide You with those services.
              </p>
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong>
              <p className="mb-4">Type: Persistent Cookies</p>
              <p className="mb-4">Administered by: Us</p>
              <p className="mb-4">
                Purpose: These Cookies identify if users have accepted the use
                of cookies on the Website.
              </p>
            </li>
            <li>
              <strong>Functionality Cookies</strong>
              <p className="mb-4">Type: Persistent Cookies</p>
              <p className="mb-4">Administered by: Us</p>
              <p className="mb-4">
                Purpose: These Cookies allow us to remember choices You make
                when You use the Website, such as remembering your login details
                or language preference. The purpose of these Cookies is to
                provide You with a more personal experience and to avoid You
                having to re-enter your preferences every time You use the
                Website.
              </p>
            </li>
            <p className="mb-4">
              For more information about the cookies we use and your choices
              regarding cookies, please visit our Cookies Policy or the Cookies
              section of our Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold mt-6 mb-3">
              Use of Your Personal Data
            </h2>
            <p className="mb-4">
              The Company may use Personal Data for the following purposes:
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>
                <strong>To provide and maintain our Service</strong>, including
                to monitor the usage of our Service.
              </li>
              <li>
                <strong>To manage Your Account:</strong> to manage Your
                registration as a user of the Service. The Personal Data You
                provide can give You access to different functionalities of the
                Service that are available to You as a registered user.
              </li>
              <li>
                <strong>For the performance of a contract:</strong> the
                development, compliance and undertaking of the purchase contract
                for the products, items or services You have purchased or of any
                other contract with Us through the Service.
              </li>
              <li>
                <strong>To contact You:</strong> To contact You by email,
                telephone calls, SMS, or other equivalent forms of electronic
                communication, such as a mobile application's push notifications
                regarding updates or informative communications related to the
                functionalities, products or contracted services, including the
                security updates, when necessary or reasonable for their
                implementation.
              </li>
              <li>
                <strong>To provide You</strong> with news, special offers and
                general information about other goods, services and events which
                we offer that are similar to those that you have already
                purchased or enquired about unless You have opted not to receive
                such information.
              </li>
              <li>
                <strong>To manage Your requests:</strong> To attend and manage
                Your requests to Us.
              </li>
              <li>
                <strong>For business transfers:</strong> We may use Your
                information to evaluate or conduct a merger, divestiture,
                restructuring, reorganization, dissolution, or other sale or
                transfer of some or all of Our assets, whether as a going
                concern or as part of bankruptcy, liquidation, or similar
                proceeding, in which Personal Data held by Us about our Service
                users is among the assets transferred.
              </li>
              <li>
                <strong>For other purposes</strong>: We may use Your information
                for other purposes, such as data analysis, identifying usage
                trends, determining the effectiveness of our promotional
                campaigns and to evaluate and improve our Service, products,
                services, marketing and your experience.
              </li>
            </ul>
            <p className="mb-4">
              We may share Your personal information in the following
              situations:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li>
                <strong>With Service Providers:</strong> We may share Your
                personal information with Service Providers to monitor and
                analyze the use of our Service, to contact You.
              </li>
              <li>
                <strong>For business transfers:</strong> We may share or
                transfer Your personal information in connection with, or during
                negotiations of, any merger, sale of Company assets, financing,
                or acquisition of all or a portion of Our business to another
                company.
              </li>
              <li>
                <strong>With Affiliates:</strong> We may share Your information
                with Our affiliates, in which case we will require those
                affiliates to honor this Privacy Policy. Affiliates include Our
                parent company and any other subsidiaries, joint venture
                partners or other companies that We control or that are under
                common control with Us.
              </li>
              <li>
                <strong>With business partners:</strong> We may share Your
                information with Our business partners to offer You certain
                products, services or promotions.
              </li>
              <li>
                <strong>With other users:</strong> when You share personal
                information or otherwise interact in the public areas with other
                users, such information may be viewed by all users and may be
                publicly distributed outside. If You interact with other users
                or register through a Third-Party Social Media Service, Your
                contacts on the Third-Party Social Media Service may see Your
                name, profile, pictures and description of Your activity.
                Similarly, other users will be able to view descriptions of Your
                activity, communicate with You and view Your profile.
              </li>
              <li>
                <strong>With Your consent</strong>: We may disclose Your
                personal information for any other purpose with Your consent.
              </li>
            </ul>

            <h2 className="text-2xl font-bold mt-6 mb-3">
              Retention of Your Personal Data
            </h2>
            <p className="mb-4">
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>
            <p className="mb-4">
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>

            <h2 className="text-2xl font-bold mt-6 mb-3">
              Transfer of Your Personal Data
            </h2>
            <p className="mb-4">
              Your information, including Personal Data, is processed at the
              Company's operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of Your state, province, country or other
              governmental jurisdiction where the data protection laws may
              differ than those from Your jurisdiction.
            </p>
            <p className="mb-4">
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer.
            </p>
            <p className="mb-4">
              The Company will take all steps reasonably necessary to ensure
              that Your data is treated securely and in accordance with this
              Privacy Policy and no transfer of Your Personal Data will take
              place to an organization or a country unless there are adequate
              controls in place including the security of Your data and other
              personal information.
            </p>
            <p className="mb-4">
              The Company shall, at the choice of the Customer, delete, access
              or transfer all the Customer Personal Data to the Customer after
              the end of the provision of Services, and deletes existing copies
              unless applicable law requires storage of the Customer Personal
              Data.
            </p>
            <p className="mb-4">
              The Company's objectives and principles in relation to Data
              Retention are to:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li>
                Set out limits for the retention of personal data and ensure
                they are complied with
              </li>
              <li>
                Ensure the Company complies fully with its obligation and rights
                of data subjects under the GDPR
              </li>
              <li>
                Ensure the safe and secure disposal of confidential data and
                information assets
              </li>
              <li>
                Ensure that records and documents are retained for the legal,
                contractual and regulatory period stated in accordance with each
                bodies rules or terms.
              </li>
              <li>
                Mitigate against risks or breaches in relation to confidential
                information
              </li>
            </ul>
            <h2 className="text-2xl font-bold mt-6 mb-3">
              Disclosure of Your Personal Data
            </h2>
            <h3 className="text-xl font-bold mt-6 mb-3">Business Transactions</h3>
            <p className="mb-4">
              If the Company is involved in a merger, acquisition or asset sale,
              Your Personal Data may be transferred. We will provide notice
              before Your Personal Data is transferred and becomes subject to a
              different Privacy Policy.
            </p>
            <h3 className="text-xl font-bold mt-6 mb-3">Law enforcement</h3>
            <p className="mb-4">
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </p>
            <h3 className="text-xl font-bold mt-6 mb-3">
              Other legal requirements
            </h3>
            <p className="mb-4">
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ul>
            <h3 className="text-xl font-bold mt-6 mb-3">
              Security of Your Personal Data
            </h3>
            <p className="mb-4">
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>
            <h1 className="text-3xl font-bold mb-4">Children's Privacy</h1>
            <p className="mb-4">
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please
              contact Us. If We become aware that We have collected Personal
              Data from anyone under the age of 13 without verification of
              parental consent, We take steps to remove that information from
              Our servers.
            </p>
            <p className="mb-4">
              If We need to rely on consent as a legal basis for processing Your
              information and Your country requires consent from a parent, We
              may require Your parent's consent before We collect and use that
              information.
            </p>
            <h1 className="text-3xl font-bold mb-4">Links to Other Websites</h1>
            <p className="mb-4">
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third party link, You will be
              directed to that third party's site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>
            <p className="mb-4">
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>

            <h1 className="text-3xl font-bold mb-4">
              Changes to this Privacy Policy
            </h1>

            <p className="mb-4">
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="mb-4">
              We will let You know via email and/or a prominent notice on Our
              Service, prior to the change becoming effective and update the
              "Last updated" date at the top of this Privacy Policy.
            </p>
            <p className="mb-4">
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
            <h2 className="text-2xl font-bold mt-6 mb-3">Contact Us</h2>
            <p className="mb-4">
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li>
                By email:{" "}
                <a
                  href="mailto:creativemashimashi@gmail.com"
                  className="text-blue-600 hover:text-blue-800"
                >
                  creativemashimashi@gmail.com
                </a>
              </li>
            </ul>

            <hr className="my-8" />

            <h1 className="text-3xl font-bold mb-4">プライバシーポリシー</h1>

            <p className="mb-4">
              このプライバシーポリシーは、サービスを利用する際のお客様の情報の収集、利用、開示に関す
              る弊社のポリシーと手続きについて説明し、お客様のプライバシー権利についてお知らせし、法
              律がお客様をどのように保護するかについて説明しています。
              私たちはサービスの提供と改善のためにお客様の個人データを使用します。サービスを利用する
              ことで、お客様はこのプライバシーポリシーに従って情報の収集と使用に同意するものとします。{" "}
            </p>

            <h1 className="text-3xl font-bold mb-4">解釈と定義</h1>

            <p className="mb-4">
              解釈
              最初の文字が大文字である単語は、以下の条件の下で定義される意味を持ちます。次の定義は、
              それらが単数形でも複数形でも表示されるかどうかにかかわらず、同じ意味を持ちます。定義このプライバシーポリシーの目的のために:{" "}
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>
                アカウント:お客様が弊社のサービスまたはサービスの一部にアクセスするために作成され
                た一意のアカウントを指します。{" "}
              </li>
              <li>
                会社(本契約書では「当社」、「弊社」、「弊社」または「当社」とも呼ばれます):
                creativemashimashiを指します。{" "}
              </li>
              <li>
                クッキー:ウェブサイトによってお客様のコンピュータ、モバイルデバイス、または他のデ
                バイスに配置され、そのウェブサイトでのお客様の閲覧履歴の詳細を含む小さなファイルで
                す。{" "}
              </li>
              <li>国:日本を指します。 </li>
              <li>
                デバイス:コンピュータ、携帯電話、またはデジタルタブレットなど、サービスにアクセス
                できる任意のデバイスを指します。{" "}
              </li>
              <li>個人データ:特定の個人に関連する情報です。 </li>
              <li>サービス:ウェブサイトを指します。 </li>
              <li>
                サービスプロバイダー:当社のデータを処理する任意の法人または自然人を指します。これ
                は、サービスを容易にするために当社に雇われたサードパーティの企業または個人を指しま
              </li>
              <li>す。 </li>
              <li>
                第三者ソーシャルメディアサービス:ユーザーがサービスを利用するためにログインしたり
                アカウントを作成したりできる任意のウェブサイトまたはソーシャルネットワークウェブサ
              </li>
              <li>イトを指します。 </li>
              <li>
                利用データ:自動的に収集されるデータであり、サービスの使用またはサービスインフラ自
                体によって生成されます(たとえば、ページ訪問の期間など)。
              </li>
              <li></li>
              <li>
                ウェブサイト:http://creativemashimashi.com
                からアクセスできるcreativemashimashiを指 します。{" "}
              </li>
              <li>
                お客様:サービスにアクセスまたは利用している個人、またはその個人がアクセスまたは利
                用している法人または他の法的実体を指します。 #
                個人データの収集および利用
              </li>
              <li>収集されるデータの種類</li>
              <li>個人データ</li>
              <li></li>
            </ul>

            <p className="mb-4">
              ⠀当社のサービスを利用する際に、お客様に連絡または識別に使用できる特定の個人情報の提供を
              お願いする場合があります。個人を特定できる情報には、以下に限定されないものの、次のもの
              が含まれる可能性があります:{" "}
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>メールアドレス </li>
              <li>名および姓 </li>
              <li>電話番号</li>
            </ul>

            <h1 className="text-3xl font-bold mb-4">利用データ</h1>

            <p className="mb-4">
              利用データは、サービスの使用時に自動的に収集されます。
              利用データには、お客様のデバイスのインターネットプロトコルアドレス(例:IPアドレス)、ブ
              ラウザのタイプ、ブラウザのバージョン、当社のサービスの訪問ページ、訪問の日時、そのページ
              に費やされた時間、一意のデバイス識別子、およびその他の診断データなどが含まれる可能性が
              あります。
              モバイルデバイスを使用してサービスにアクセスする場合、当社は特定の情報を自動的に収集する
              ことがあります。これには、使用しているモバイルデバイスのタイプ、モバイルデバイスの一意の
              ID、モバイルデバイスのIPアドレス、モバイルオペレーティングシステム、使用しているモバイル
              インターネットブラウザのタイプ、一意のデバイス識別子、およびその他の診断データなどが含ま
              れる可能性があります。
              当社のサービスにアクセスする際やモバイルデバイスを通じてサービスにアクセスする際に、ブラ
              ウザが当社のサービスにアクセスしたときやアクセスしたときの情報も収集することがあります。
              トラッキング技術およびクッキー
              当社はクッキーおよび同様のトラッキング技術を使用して、当社のサービスのアクティビティを追
              跡し、特定の情報を保存します。使用されるトラッキング技術には、ビーコン、タグ、およびスク
              リプトが含まれ、情報を収集し、追跡してサービスを改善および分析します。当社が使用する技
              術には以下が含まれる可能性があります:{" "}
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>
                クッキーまたはブラウザクッキー:クッキーはデバイスに配置される小さなファイルです。
                ブラウザに対してすべてのクッキーを拒否するか、クッキーが送信される際に通知するよう
                にブラウザに指示することができます。ただし、クッキーを受け入れない場合、サービスの
                一部を利用できない可能性があります。ブラウザ設定を調整してクッキーを拒否するように
                していない限り、当社のサービスはクッキーを使用する可能性があります。{" "}
              </li>
              <li>
                フラッシュクッキー:当社のサービスの一部には、ローカルストレージオブジェクト(また
                はフラッシュクッキー)を使用してお客様の設定やサービス上のアクティビティに関する情
                報を収集および保存することがあります。フラッシュクッキーはブラウザクッキーとは異な
                るブラウザ設定で管理されます。フラッシュクッキーを削除する方法についての詳細は、
                「Flash
                Cookiesを無効にするまたは削除するための設定を変更できる場所はどこです
                か?」を参照してください。Adobeのヘルプ{" "}
              </li>
              <li>
                ウェブビーコン:当社のサービスやメールの一部には、ウェブビーコン(クリアギフ、ピク
                セルタグ、およびシングルピクセルギフとも呼ばれる)として知られる小さな電子ファイル
                が含まれることがあります。これにより、当社は例えば、それらのページを訪れたユーザー
                の数やメールを開封したユーザーの数などを数えることができ、関連するウェブサイトの統
                計情報(特定のセクションの人気を記録し、システムおよびサーバーの整合性を確認するな
                ど)が得られます。{" "}
              </li>
            </ul>

            <p className="mb-4">
              ⠀クッキーの種類
              クッキーは「永続的な」または「セッション」クッキーに分類されます。永続的なクッキーは、
              オフラインになってもお客様のパーソナルコンピュータまたはモバイルデバイスに残りますが、
              セッションクッキーはウェブブラウザを閉じるとすぐに削除されます。クッキーについての詳細
              はこちらで確認できます:TermsFeedによるAll About Cookies
              当社は以下の目的のためにセッションおよび永続的なクッキーの両方を使用しています:{" "}
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>
                必須 / エッセンシャルクッキー
                <ul className="list-disc list-inside mb-4">
                  <li>タイプ: セッションクッキー </li>
                  <li>管理者: 当社 </li>
                  <li>
                    目的:
                    これらのクッキーはウェブサイトを通じて提供されるサービスを提供し、そ
                    の機能の一部を利用できるようにするために不可欠です。これらのクッキーはユー
                    ザーを認証し、ユーザーアカウントの不正使用を防ぐのに役立ちます。これらのクッ
                    キーがないと、お客様が要求したサービスを提供できず、これらのサービスの提供に
                    のみこれらのクッキーを使用します。{" "}
                  </li>
                </ul>
              </li>
              <li>
                クッキーポリシー / 注意受け入れクッキー
                <ul className="list-disc list-inside mb-4">
                  <li>タイプ: 永続的なクッキー </li>
                  <li>管理者: 当社 </li>
                  <li>
                    目的:
                    これらのクッキーはユーザーがウェブサイトでクッキーの使用を受け入れた
                    かどうかを識別します。{" "}
                  </li>
                </ul>
              </li>
              <li>
                機能クッキー
                <ul className="list-disc list-inside mb-4">
                  <li>タイプ: 永続的なクッキー </li>
                  <li>管理者: 当社 </li>
                  <li>
                    目的:
                    これらのクッキーは、ウェブサイトを使用する際にお客様が行った選択を覚
                    えておくことができます。例えば、ログインの詳細や言語の選択を覚えておくことが
                    できます。これらのクッキーの目的は、お客様によりパーソナルなエクスペリエンス
                    を提供し、ウェブサイトを使用するたびに設定を再入力する必要がないようにするこ
                    とです。
                    クッキーに関する詳細およびクッキーに関するお客様の選択については、当社のクッキーポリ
                  </li>
                  <li>
                    シーまたはプライバシーポリシーのクッキーセクションをご覧ください。
                  </li>
                </ul>
              </li>
            </ul>

            <h1 className="text-3xl font-bold mb-4">個人データの利用</h1>

            <p className="mb-4">
              会社は、個人データを以下の目的で使用することがあります:
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>
                サービスの提供と維持、サービスの利用状況の監視を含む。{" "}
              </li>
              <li>
                アカウントの管理:サービスのユーザーとしての登録の管理。提供された個人データによ
                り、登録ユーザーとして利用可能なサービスの異なる機能にアクセスできるようになりま
                す。{" "}
              </li>
              <li>
                契約の履行:製品、アイテム、またはサービスの購入契約やサービスを通じて弊社とのその
                他の契約の開発、順守、および実施。
              </li>
              <li></li>
              <li>
                連絡先の確立:電子メール、電話、SMS、モバイルアプリケーションのプッシュ通知など、
                電子コミュニケーションの同等の形式を使用して、機能、製品、または契約サービスに関連
                する更新や情報通信に関する連絡。{" "}
              </li>
              <li>
                ニュース、特別オファー、および既に購入または問い合わせを行った商品、サービス、およ
                びイベントに関する一般情報を提供するため。{" "}
              </li>
              <li>リクエストの管理:弊社へのリクエストの対応および管理。 </li>
              <li>
                ビジネスの譲渡:弊社の資産の一部または全部を統合、売却、再構築、再編成、解散、また
                は同様の手続きの一環として、営業としての継続または破産、清算など、個人データが弊社
                のサービスユーザーに関する資産の一部として転送される場合があります。{" "}
              </li>
              <li>
                その他の目的:データ分析、利用動向の特定、プロモーションキャンペーンの効果の判断、
                サービス、製品、サービス、マーケティング、および体験の評価と改善など、その他の目的
                で個人情報を使用する場合があります。
                個人情報は以下の状況で共有される可能性があります:{" "}
              </li>
              <li>
                サービスプロバイダーとの共有:サービスの利用状況をモニターし分析するために、また連
                絡を取るために、個人情報をサービスプロバイダーと共有することがあります。{" "}
              </li>
              <li>
                ビジネスの譲渡:企業資産の一部または全部を別の会社に譲渡するため、またはその交渉中
                に、個人情報を共有または転送することがあります。{" "}
              </li>
              <li>
                アフィリエイトとの共有:アフィリエイトと個人情報を共有する場合、アフィリエイトには
                このプライバシーポリシーを遵守するように要求します。アフィリエイトには親会社やその
                他の子会社、合弁事業パートナー、または当社と共同制御または共通の制御下にある他の会
                社が含まれます。{" "}
              </li>
              <li>
                ビジネスパートナーとの共有:特定の製品、サービス、またはプロモーションを提供するた
                めに、ビジネスパートナーと情報を共有することがあります。{" "}
              </li>
              <li>
                他のユーザーとの共有:他のユーザーと個人情報を共有したり、公共の場で相互作用したり
                する場合、その情報はすべてのユーザーに表示され、公然と配布される可能性があります。
                サードパーティのソーシャルメディアサービスを介して他のユーザーと連携する場合、その
                サービス上でのお名前、プロフィール、写真、および活動の説明が閲覧可能です。同様に、
                他のユーザーは活動の説明を表示し、連絡を取り合い、プロフィールを閲覧できるでしょ
                う。{" "}
              </li>
              <li>
                ご同意を得ての共有:お客様の同意が得られた場合、個人情報を他の目的で開示することが
                あります。{" "}
              </li>
            </ul>

            <h1 className="text-3xl font-bold mb-4">個人データの保持</h1>

            <p className="mb-4">
              会社は、このプライバシーポリシーで述べられた目的のために必要な限りの期間だけ、お客様の
              個人データを保持します。法的義務を遵守する必要がある場合(たとえば、適用される法律を遵
              守するためにデータを保持する必要がある場合)、紛争の解決、および法的契約とポリシーの執
              行に必要な範囲で個人データを保持および使用します。
              会社はまた、内部分析の目的で利用データを保持します。利用データは通常、短い期間保持され
              ますが、このデータがセキュリティの強化やサービスの機能の向上に使用される場合、または法
              的に長期間データを保持する法的義務がある場合を除きます。
            </p>

            <h1 className="text-3xl font-bold mb-4">個人データの転送</h1>

            <p className="mb-4">
              お客様の情報、個人データを含むものは、会社の運営拠点および処理に関与する他の場所で処理
              されます。これは、この情報がお客様の属する州、省、国、またはその他の政府管轄区域とは異{" "}
            </p>

            <p className="mb-4">
              ⠀なる場所にあるコンピュータに転送および維持される可能性があることを意味します。データ保
              護法がお客様の管轄区域とは異なる可能性があります。
              このプライバシーポリシーに同意し、その情報を提出することに続くお客様の同意は、その転送
              に同意したものと見なされます。
              会社は合理的な手段を講じて、お客様のデータがこのプライバシーポリシーに基づいて安全に取
              り扱われ、お客様のデータおよび他の個人情報のセキュリティを含む十分なコントロールがない
              限り、お客様の個人データが組織または国に転送されないようにします。
              サービス提供終了後、会社はお客様の選択に基づいて、サービス提供終了後にお客様の個人デー
              タを削除、アクセス、またはお客様に転送し、該当する法律がお客様の個人データの保存を要求
              しない限り、既存のコピーを削除します。
              データ保持に関する会社の目的と原則は以下のとおりです:{" "}
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>個人データの保持期間を定め、これを遵守する </li>
              <li>GDPRに基づくデータ主体の権利と義務を完全に遵守する </li>
              <li>
                機密データおよび情報資産の安全かつ安全な廃棄を確保する{" "}
              </li>
              <li>
                各機関の規則または条件に従って法的、契約上、規制上の期間にわたり記録と文書を保持す
                る{" "}
              </li>
              <li>
                機密情報に関するリスクや侵害に対処する # 個人データの開示
              </li>
              <li>事業取引</li>
              <li>
                <p className="mb-4">
                  会社が合併、買収、または資産の売却に関与する場合、お客様の個人データが転送される可能性
                  があります。お客様の個人データが転送され、異なるプライバシーポリシーの対象となる前にお
                  知らせします。{" "}
                </p>

                <h1 className="text-3xl font-bold mb-4">法執行機関</h1>

                <p className="mb-4">
                  一定の状況下で、会社は法に従うか、公権力(たとえば、裁判所や政府機関)からの妥当な要求
                  に応じて、お客様の個人データを開示する必要がある場合があります。{" "}
                </p>

                <h1 className="text-3xl font-bold mb-4">その他の法的要件</h1>

                <p className="mb-4">
                  会社は、次のような状況で、お客様の個人データを善意の信念に基づいて開示する可能性があります:
                </p>
              </li>
              <li>法的な義務を遵守するため</li>
              <li>会社の権利や財産を保護し、防衛するため</li>
              <li>
                サービスに関連する可能性のある不正行為を防ぎ、調査するため
              </li>
              <li>
                サービスの利用者または一般の人々の個人の安全を保護するため
                <li>法的責任に対抗するため</li>
              </li>
            </ul>

            <h1 className="text-3xl font-bold mb-4">個人データのセキュリティ</h1>

            <p className="mb-4">
              個人データのセキュリティは弊社にとって重要ですが、インターネットを介した伝送方法や電子
              的な保存方法が100%安全であることを覚えておいてください。弊社は個人データを保護するために商業的に受け入れられる手段を尽くしていますが、その絶対的なセキュリティを保証すること
              はできません。
            </p>

            <h1 className="text-3xl font-bold mb-4">子どものプライバシー</h1>

            <p className="mb-4">
              弊社のサービスは、13歳未満の個人を対象としていません。われわれは故意に13歳未満の個人か
              ら個人を特定できる情報を収集しません。もし、親または保護者であり、お子様が弊社に個人
              データを提供したことを知っている場合は、お問い合わせください。もし、13歳未満の個人から
              親権者の同意を確認せずに個人データを収集したことがわかった場合は、その情報を弊社のサー
              バーから削除する措置を講じます。
              もし、お客様の情報の処理に法的根拠として同意が必要で、お客様の国が親の同意を要求する場
              合、その情報を収集および利用する前にお客様の親の同意を必要とすることがあります。{" "}
            </p>

            <h1 className="text-3xl font-bold mb-4">
              他のウェブサイトへのリンク
            </h1>

            <p className="mb-4">
              弊社のサービスには、弊社が運営していない他のウェブサイトへのリンクが含まれている場合が
              あります。サードパーティのリンクをクリックすると、そのサードパーティのサイトに移動しま
              す。すべての訪れるサイトのプライバシーポリシーを確認することを強くお勧めします。
              弊社はサードパーティのサイトやサービスの内容、プライバシーポリシー、または実践について制
              御せず、一切の責任を負いません。
            </p>

            <h1 className="text-3xl font-bold mb-4">
              このプライバシーポリシーの変更
            </h1>

            <p className="mb-4">
              弊社は定期的にプライバシーポリシーを更新する場合があります。新しいプライバシーポリシーを
              掲載することで変更をお知らせします。
              変更が有効となる前に、電子メールおよび/またはサービス上で目立つ通知を行い、このプライバ
              シーポリシーのトップに「最終更新日」を更新します。
              お客様は変更があるかどうかを定期的に確認することをお勧めします。このプライバシーポリシー
              の変更は、このページに掲載された時点で有効となります。{" "}
            </p>

            <h1 className="text-3xl font-bold mb-4">お問い合わせ</h1>

            <p className="mb-4">
              このプライバシーポリシーに関するご質問がある場合は、以下からお問い合わせいただけます:{" "}
            </p>

            <p className="mb-4">メール:creativemashimashi@gmail.com </p>
          </div>
        </main>
      </div>
    </>
  );
}

export default MontenPrivacyPolicy;
